version: '3.8'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'application'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  mysql_data: